-- 코드를 입력하세요
SELECT LEFT(SALES_DATE,10), PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE LEFT(SALES_DATE,7) = '2022-03'
UNION ALL
SELECT LEFT(SALES_DATE,10), PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE LEFT(SALES_DATE,7) = '2022-03'
ORDER BY 1, 2, 3