-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
JOIN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed %' OR SEX_UPON_OUTCOME LIKE 'Neutered %'
) AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE NOT LIKE 'Spayed %' AND AI.SEX_UPON_INTAKE NOT LIKE 'Neutered %'
ORDER BY ANIMAL_ID
