-- 코드를 입력하세요
SELECT 
    HISTORY_ID, CAR_ID, LEFT(START_DATE,10), LEFT(END_DATE,10),
    CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '장기 대여' ELSE '단기 대여' END
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE LEFT(START_DATE,7) = '2022-09'
ORDER BY HISTORY_ID DESC