-- 코드를 입력하세요
SELECT A.PRODUCT_ID, B.PRODUCT_NAME, A.AMOUNT * B.PRICE TOTAL_SALES
FROM (SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
FROM FOOD_ORDER
WHERE LEFT(PRODUCE_DATE,7) = '2022-05'
GROUP BY PRODUCT_ID) A
JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID